# Example YAML file demonstrating experiment config
---
metadata:
  experiment_id: "test_experiment"
  seed: 0 # Random seed
  iteration: 0 # Initial iteration
  end_iteration: 1 # Iteration to end on
  
  new_timestamped_log : true 
  new_timestamped_checkpoint_dir : true 
  log_dir : "results" # Top-level logging directory
  checkpoint_dir : "results" # Top-level checkpoint dir
  
  debug: false 
  logging_verbosity: 10 # Logging level: use Python Logger.

data:
  # Dummy dataset to demonstrate initialization.
  - handler : "test_ordered"
    params:
      id : "train"
      shuffle: false
      num_to_initialize: 10
  - handler : "test_ordered"
    params:
      id : "test"
      shuffle: false
      num_to_initialize: 5
      
models:
  # Dummy model to demonstrate initialization.
  - handler : "test_model"
    params:
      id : "test_model"
      
experiment:
  # Increment the task batch.
  - data: "train"
    fn: "get_batch"
    params:
      batch_size: 10
  # Update the model with the task batch.
  - models: "test_model"
    fn : "update"
    params:
      data: 
        - id: "train"
          batch: true
  # Evaluate the model on heldout data
  - models: "test_model"
    fn: "evaluate_loss"
    params:
      data:
        - id: "test"

  # Checkpoint everything.
  - checkpoint:
      metadata: 
        - iteration
      data : 
        - all
      models : 
        - all